/* ============================================================================
   FIX: USP_IMP_WMS_GOODSRETURN_INSERT_DTLS
   ----------------------------------------------------------------------------
   BUG (root cause of the OVERSTATED currentstock rows):
   Every stock-adjust block against WMS_ITEM_STOCK_MASTER_COMMON_CONTR joined
   the stock table INSIDE the SUM() subquery on FK_ITEMID only — no container
   match. An item stored in N containers therefore multiplied the summed
   RETURNQTY by N before applying it, e.g. return of 20 on an item in 2
   containers added 40 (proven in prod: EAN 3616035872832 / TRHU4806138, and
   383 of the 700 overstated rows are exact multiples of their return qty).

   FIXES in this version:
   1. All COMMON_CONTR subqueries group by (FK_ITEMID, CONTAINERNO) and the
      outer join matches BOTH keys. The stock table is no longer joined inside
      the subquery, so no row multiplication is possible.
   2. The post-delete reversal blocks (previously per-row, no SUM) now
      aggregate, so multiple deleted lines for the same item apply fully
      (UPDATE...FROM silently applies only ONE row when B has duplicates).
   3. BALANCESTOCK wrapped in ISNULL to avoid NULL propagation.
   Everything else (temp-table flow, inserts, edits, deletes, usertrack) is
   byte-identical in behaviour to the original.
   ============================================================================ */

ALTER PROCEDURE [dbo].[USP_IMP_WMS_GOODSRETURN_INSERT_DTLS]
 @ID VARCHAR(2),
 @GRTNNO VARCHAR(15),
 @VGUID NVARCHAR(200),
 @TRACKID INTEGER,
 @MAKER_ID NVARCHAR(50),
 @MAKER_IP NVARCHAR(50),
 @ACTION  NVARCHAR(20)

AS

DECLARE @CHILDTRACK INT
  IF OBJECT_ID('TEMPDB..#TMPGOODSRETURN_DTLS') IS NOT NULL
DROP TABLE  #TMPGOODSRETURN_DTLS

CREATE TABLE #TMPGOODSRETURN_DTLS (
id INT IDENTITY(1,1),
fk_grtnno VARCHAR(15),
fk_itemid INT,
returnqty DECIMAL(18,2),
uom VARCHAR(15),
FK_RETURNREASON int,
containerno varchar(30)
)

BEGIN

		IF(@ACTION='UPDATE')
			BEGIN
			INSERT INTO  #TMPGOODSRETURN_DTLS select fk_grtnno,fk_itemid,returnqty,uom,FK_RETURNREASON,containerno from
		    TBL_IMP_WMS_GOODSRETURN_DTLS  WHERE FK_GRTNNO = @GRTNNO  ORDER BY ID

			/* reverse out previously-posted return qty (item level) */
			UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)-B.RETURNQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)-B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID FROM #TMPGOODSRETURN_DTLS  DTLS
			WHERE DTLS.FK_RETURNREASON=1 AND DTLS.FK_GRTNNO=@GRTNNO
			GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID

			/* reverse out previously-posted return qty (item + container level)
			   FIX: join on FK_ITEMID AND CONTAINERNO — no stock-table self-join */
			UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)-B.RETURNQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)-B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM #TMPGOODSRETURN_DTLS  DTLS
			WHERE DTLS.FK_RETURNREASON=1 AND DTLS.FK_GRTNNO=@GRTNNO
			GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID AND A.CONTAINERNO=B.CONTAINERNO
			END
-- Inserting new records into the main table
						INSERT INTO TBL_IMP_WMS_GOODSRETURN_DTLS (
							fk_grtnno,
							FK_ITEMID,
							RETURNQTY,
							UOM,
							EAN,
							FK_RETURNREASON,
							FK_RETURNTYPE,
							CONTAINERNO,
							BOXNO,
							KIABICODE
						)
						SELECT
							@GRTNNO,
							FK_ITEMID,
							RETURNQTY,
							UOM,
							EAN,
							FK_RETURNREASON,
							FK_RETURNTYPE,
							CONTAINERNO,
							ISNULL(BOXNO,''),
							ISNULL(KIABICODE,'')
							FROM
							TBL_IMP_WMS_GOODSRETURN_DTLS_TMP
						WHERE
							VGUID = @VGUID
							AND ISDELETED <> 'Y'
							AND GRTNDTLSID = 0


			 UPDATE TBL_IMP_WMS_GOODSRETURN_DTLS
		   SET
		   TBL_IMP_WMS_GOODSRETURN_DTLS.FK_ITEMID = TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.FK_ITEMID,
		   TBL_IMP_WMS_GOODSRETURN_DTLS.RETURNQTY = TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.RETURNQTY,
		   TBL_IMP_WMS_GOODSRETURN_DTLS.UOM = TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.UOM
		   FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP
		   WHERE TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.GRTNDTLSID =TBL_IMP_WMS_GOODSRETURN_DTLS.ID
		   AND TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.VGUID = @VGUID   AND ISDELETED <> 'Y'

		   	 /* UPDATING CURRENT & OPENING STOCK */

		  	UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)+B.RETURNQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)+B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSRETURN_DTLS  DTLS
			WHERE DTLS.FK_RETURNREASON=1 AND DTLS.FK_GRTNNO=@GRTNNO
			GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID

		     /* END UPDATING CURRENT STOCK */

			 	 /* UPDATING CURRENT & OPENING STOCK IN COMMON CONTAINER
			 	    FIX: join on FK_ITEMID AND CONTAINERNO — no stock-table self-join */

		  	UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)+B.RETURNQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)+B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSRETURN_DTLS  DTLS
			WHERE DTLS.FK_RETURNREASON=1 AND DTLS.FK_GRTNNO=@GRTNNO
			GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID AND A.CONTAINERNO=B.CONTAINERNO

		     /* END UPDATING CURRENT STOCK */


			DELETE FROM TBL_IMP_WMS_GOODSRETURN_DTLS  WHERE FK_GRTNNO = @GRTNNO
			AND ID IN (SELECT GRTNDTLSID FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP WHERE VGUID = @VGUID AND ISDELETED = 'Y')

			/* back out qty of deleted lines (item level)
			   FIX: aggregated — original applied only one arbitrary row */
		   	UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)-B.RETURNQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)-B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP  DTLS
			WHERE DTLS.VGUID = @VGUID AND DTLS.ISDELETED = 'Y' AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO
			GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID

			/* back out qty of deleted lines (item + container level)
			   FIX: aggregated + container-matched */
			UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)-B.RETURNQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)-B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP  DTLS
			WHERE DTLS.VGUID = @VGUID AND DTLS.ISDELETED = 'Y' AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO
			GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID  AND A.CONTAINERNO=B.CONTAINERNO


			 INSERT INTO TBL_USERTRACK_DETAILS(
				   FKTRACKID, USERID, [DATETIME],  MODE, TABLENAME,  COLUMNNAME,
				   ORIGINALDATA, MODIFIEDDATA, RECORDID, LOCALIPADD,  ROUTERIPADD)
				  SELECT  @TRACKID,@MAKER_ID,GETDATE(),
					CASE WHEN GRTNDTLSID <> '0' AND ISDELETED = 'Y' THEN 'DELETE'
					 WHEN GRTNDTLSID = '0' AND ISDELETED <> 'Y' THEN 'ADD'
					 ELSE 'EDIT'
				     END,
				   'TBL_IMP_WMS_GOODSRETURN_DTLS',
				   USERTRACK_COLUMNNAME,
				   USERTRACK_ORIGINALDATA,
				   USERTRACK_MODIFIEDDATA,
				   @GRTNNO,
				   @MAKER_IP,
				   ''
				 FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP
				 WHERE VGUID = @VGUID
				   AND ((ISNULL(USERTRACK_MODIFIEDDATA,'') <> '' AND  GRTNDTLSID<>'0') OR
					 (ISDELETED='Y' AND GRTNDTLSID <> '0') OR
					 (GRTNDTLSID = '0' AND ISDELETED <> 'Y'))
		END

IF @ACTION = 'INSERT'
		BEGIN
		 DELETE FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP WHERE VGUID = @VGUID
		END
ELSE --IF @ACTION = 'UPDATE'
BEGIN
  	DELETE FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP WHERE VGUID = @VGUID
  BEGIN
	 INSERT INTO TBL_IMP_WMS_GOODSRETURN_DTLS_TMP
		SELECT FK_GRTNNO,
		FK_ITEMID,
		RETURNQTY,
		UOM,
		EAN,
		FK_RETURNREASON,
		FK_RETURNTYPE,
		GIDTLS.ID,
		'',
		'N',
        'GRTNNO|FK_ITEMID|QTY|UOM|SIZE',
		 fk_grtnno + '|' + CONVERT(VARCHAR,FK_ITEMID)  + '|' +  CONVERT(VARCHAR,RETURNQTY) + '|' +  CONVERT(VARCHAR,UOM)  ,
		'',
        @MAKER_ID,
		@VGUID,
		CONTAINERNO,
		ISNULL(BOXNO,''),
		ISNULL(KIABICODE,'')

		FROM TBL_IMP_WMS_GOODSRETURN_DTLS   GIDTLS
		INNER JOIN TBL_IMP_WMS_GOODSRETURN_MST GIMST ON GIMST.GRTNNO=GIDTLS.FK_GRTNNO
		WHERE GIDTLS.FK_GRTNNO = @GRTNNO
		ORDER BY GIDTLS .ID
 END
END
