/* ============================================================================
   FIX: USP_IMP_WMS_GOODSISSUE_INSERT_DTLS
   ----------------------------------------------------------------------------
   BUGS:
   1. Every stock adjustment was wrapped in
        CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK ± B.QTY) ELSE 0 END
      The clamp makes edits NON-REVERSIBLE: when stock sits at 0 the
      reverse-out step silently no-ops, so editing/deleting an issue line
      after stock reached 0 loses the adjustment → understated stock.
      Negative intermediate states are legitimate during a reverse/re-apply
      cycle; hiding them corrupts the ledger.
   2. The post-delete item-level block had no SUM/GROUP BY — with several
      deleted lines for one item, UPDATE...FROM applies only ONE arbitrary
      row.
   3. COMMON_CONTR blocks joined the stock table inside the subquery and put
      the container match in a WHERE after the JOIN — worked, but rewritten
      to the same safe aggregate-then-join pattern as the other fixed SPs.

   FIXES: plain ISNULL(x,0) ± qty arithmetic everywhere, aggregated
   subqueries grouped by (FK_ITEMID [, CONTAINERNO]), outer joins match all
   grouping keys. Flow otherwise identical.
   ============================================================================ */

ALTER PROCEDURE [dbo].[USP_IMP_WMS_GOODSISSUE_INSERT_DTLS]
 @ID VARCHAR(2),
 @GINNO VARCHAR(15),
 @VGUID NVARCHAR(200),
 @TRACKID INTEGER,
 @MAKER_ID NVARCHAR(50),
 @MAKER_IP NVARCHAR(50),
 @ACTION  NVARCHAR(20)

AS

DECLARE @CHILDTRACK INT
  IF OBJECT_ID('TEMPDB..#TMPGOODSISSUE_DTLS ') IS NOT NULL
DROP TABLE  #TMPGOODSISSUE_DTLS

CREATE TABLE #TMPGOODSISSUE_DTLS (
id INT IDENTITY(1,1),
fk_ginno VARCHAR(15),
fk_itemid INT,
issueqty DECIMAL(18,2),
uom VARCHAR(15),
containerno varchar(30)
)

BEGIN

		IF(@ACTION='UPDATE')
			BEGIN
			INSERT INTO  #TMPGOODSISSUE_DTLS select fk_ginno,fk_itemid,issueqty,uom,containerno from
		    TBL_IMP_WMS_GOODSISSUE_DTLS  WHERE FK_GINNO = @GINNO  ORDER BY ID

			/* reverse out previously-posted issue qty (item level) — FIX: no clamp */
			UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)+B.ISSUEQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)+B.ISSUEQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID FROM #TMPGOODSISSUE_DTLS  DTLS
			WHERE DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID

			/* reverse out previously-posted issue qty (item + container) — FIX: no clamp */
			UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)+B.ISSUEQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)+B.ISSUEQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM #TMPGOODSISSUE_DTLS  DTLS
			WHERE DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID AND A.CONTAINERNO=B.CONTAINERNO
			END
-- Inserting new records into the main table
						INSERT INTO TBL_IMP_WMS_GOODSISSUE_DTLS (
							fk_ginno,
							FK_ITEMID,
							ISSUEQTY,
							UOM,
							EAN,
							BOXNO,
							CONTAINERNO
						)
						SELECT
							@GINNO,
							FK_ITEMID,
							ISSUEQTY,
							UOM,
							EAN,
							BOXNO,
							CONTAINERNO
						FROM
							TBL_IMP_WMS_GOODSISSUE_DTLS_TMP
						WHERE
							VGUID = @VGUID
							AND ISDELETED <> 'Y'
							AND GINDTLSID = 0


			 UPDATE TBL_IMP_WMS_GOODSISSUE_DTLS
		   SET
		   TBL_IMP_WMS_GOODSISSUE_DTLS.ISSUEQTY = TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.ISSUEQTY,
		   TBL_IMP_WMS_GOODSISSUE_DTLS.UOM = TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.UOM,
		   TBL_IMP_WMS_GOODSISSUE_DTLS.BOXNO=TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.BOXNO
		   FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP
		   WHERE TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.GINDTLSID = TBL_IMP_WMS_GOODSISSUE_DTLS.ID
		   AND TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.VGUID = @VGUID   AND ISDELETED <> 'Y'

		   		   /* UPDATING CURRENT & OPENING STOCK — FIX: no clamp */

		  	UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)-B.ISSUEQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)-B.ISSUEQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSISSUE_DTLS  DTLS
			WHERE DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID

		     /* END UPDATING CURRENT STOCK */

			   /* UPDATING CURRENT & OPENING STOCK IN COMMON CONTAINER — FIX: no clamp */

		  	UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)-B.ISSUEQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)-B.ISSUEQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSISSUE_DTLS  DTLS
			WHERE DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID  AND A.CONTAINERNO=B.CONTAINERNO

		     /* END UPDATING CURRENT STOCK */


			DELETE FROM TBL_IMP_WMS_GOODSISSUE_DTLS  WHERE FK_GINNO = @GINNO
			AND ID IN (SELECT GINDTLSID FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP WHERE VGUID = @VGUID AND ISDELETED = 'Y')

			/* add back qty of deleted lines (item level)
			   FIX: aggregated (was per-row) + no clamp */
		   	UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)+B.ISSUEQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)+B.ISSUEQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP  DTLS
			WHERE DTLS.VGUID = @VGUID AND DTLS.ISDELETED = 'Y'
			AND DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID

			/* add back qty of deleted lines (item + container) — FIX: no clamp */
			UPDATE  A SET A.CURRENTSTOCK=ISNULL(A.CURRENTSTOCK,0)+B.ISSUEQTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)+B.ISSUEQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP  DTLS
			WHERE DTLS.VGUID = @VGUID AND DTLS.ISDELETED = 'Y'
			AND DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID AND A.CONTAINERNO=B.CONTAINERNO

			 INSERT INTO TBL_USERTRACK_WMS_DETAILS(
				   FKTRACKID, USERID, [DATETIME],  MODE, TABLENAME,  COLUMNNAME,
				   ORIGINALDATA, MODIFIEDDATA, RECORDID, LOCALIPADD,  ROUTERIPADD)
				  SELECT  @TRACKID,@MAKER_ID,GETDATE(),
					CASE WHEN GINDTLSID <> '0' AND ISDELETED = 'Y' THEN 'DELETE'
					 WHEN GINDTLSID = '0' AND ISDELETED <> 'Y' THEN 'ADD'
					 ELSE 'EDIT'
				     END,
				   'TBL_IMP_WMS_GOODSISSUE_DTLS',
				   USERTRACK_COLUMNNAME,
				   USERTRACK_ORIGINALDATA,
				   USERTRACK_MODIFIEDDATA,
				   @GINNO,
				   @MAKER_IP,
				   ''
				 FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP
				 WHERE VGUID = @VGUID
				   AND ((ISNULL(USERTRACK_MODIFIEDDATA,'') <> '' AND  GINDTLSID<>'0') OR
					 (ISDELETED='Y' AND GINDTLSID <> '0') OR
					 (GINDTLSID = '0' AND ISDELETED <> 'Y'))
		END

IF @ACTION = 'INSERT'
		BEGIN
		 DELETE FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP WHERE VGUID = @VGUID
		END
ELSE --IF @ACTION = 'UPDATE'
BEGIN
  	DELETE FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP WHERE VGUID = @VGUID
  BEGIN
	 INSERT INTO TBL_IMP_WMS_GOODSISSUE_DTLS_TMP
		SELECT FK_GINNO,
		FK_ITEMID,
		ISSUEQTY,
		UOM,
		GIDTLS.ID,
		'',
		'N',
        'GINNO|FK_ITEMID|QTY|UOM|SIZE',
		FK_GINNO + '|' + CONVERT(VARCHAR,FK_ITEMID)  + '|' +  CONVERT(VARCHAR,ISSUEQTY) + '|' +  CONVERT(VARCHAR,UOM)  ,
		'',
        @MAKER_ID,
		@VGUID,
		EAN,
		BOXNO=GIDTLS.BOXNO,
		ISSUEQTY,
		ISNULL(ACKNO,''),GIDTLS.CONTAINERNO
		FROM TBL_IMP_WMS_GOODSISSUE_DTLS   GIDTLS
		INNER JOIN TBL_IMP_WMS_GOODSISSUE_MST GIMST ON GIMST.GINNO=GIDTLS.FK_GINNO
		WHERE GIDTLS.FK_GINNO = @GINNO
		ORDER BY GIDTLS .ID
 END
END
