/* ============================================================================
   PREVIEW (read-only): currentstock drift in WMS_ITEM_STOCK_MASTER_COMMON_CONTR
   Shows what 07_repair_currentstock.sql would change. Safe to run anytime.
   Authoritative balance = GRN − issued + returned per (FK_ITEMID, CONTAINERNO),
   container for GRN taken from TBL_IMP_WMS_GRN_MASTER.
   ============================================================================ */
SET NOCOUNT ON;

;WITH GRN AS (
    SELECT D.FK_ITEMID, M.CONTAINERNO, QTY = SUM(D.QTY)
    FROM TBL_IMP_WMS_GRN_DTLS D
    INNER JOIN TBL_IMP_WMS_GRN_MASTER M ON M.GRNNO = D.GRNNO
    GROUP BY D.FK_ITEMID, M.CONTAINERNO),
ISS AS (
    SELECT FK_ITEMID, CONTAINERNO, QTY = SUM(ISSUEQTY)
    FROM TBL_IMP_WMS_GOODSISSUE_DTLS
    GROUP BY FK_ITEMID, CONTAINERNO),
RTN AS (
    SELECT FK_ITEMID, CONTAINERNO, QTY = SUM(RETURNQTY)
    FROM TBL_IMP_WMS_GOODSRETURN_DTLS
    GROUP BY FK_ITEMID, CONTAINERNO),
X AS (
    SELECT S.EAN, S.FK_ITEMID, S.containerno,
           CURRENTSTOCK = ISNULL(S.CURRENTSTOCK, 0),
           BALANCESTOCK = ISNULL(S.BALANCESTOCK, 0),
           NEWSTOCK = ISNULL(G.QTY,0) - ISNULL(I.QTY,0) + ISNULL(R.QTY,0)
    FROM WMS_ITEM_STOCK_MASTER_COMMON_CONTR S
    LEFT JOIN GRN G ON G.FK_ITEMID = S.FK_ITEMID AND G.CONTAINERNO = S.containerno
    LEFT JOIN ISS I ON I.FK_ITEMID = S.FK_ITEMID AND I.CONTAINERNO = S.containerno
    LEFT JOIN RTN R ON R.FK_ITEMID = S.FK_ITEMID AND R.CONTAINERNO = S.containerno)

/* 1. summary */
SELECT bucket = CASE WHEN CURRENTSTOCK > NEWSTOCK THEN 'OVERSTATED'
                     WHEN CURRENTSTOCK < NEWSTOCK THEN 'UNDERSTATED'
                     ELSE 'OK' END,
       rows_affected = COUNT(*),
       stored_units  = SUM(CURRENTSTOCK),
       real_units    = SUM(NEWSTOCK),
       delta_units   = SUM(CURRENTSTOCK - NEWSTOCK)
FROM X
GROUP BY CASE WHEN CURRENTSTOCK > NEWSTOCK THEN 'OVERSTATED'
              WHEN CURRENTSTOCK < NEWSTOCK THEN 'UNDERSTATED'
              ELSE 'OK' END
ORDER BY 1;

/* 2. every row the repair would touch */
;WITH GRN AS (
    SELECT D.FK_ITEMID, M.CONTAINERNO, QTY = SUM(D.QTY)
    FROM TBL_IMP_WMS_GRN_DTLS D
    INNER JOIN TBL_IMP_WMS_GRN_MASTER M ON M.GRNNO = D.GRNNO
    GROUP BY D.FK_ITEMID, M.CONTAINERNO),
ISS AS (
    SELECT FK_ITEMID, CONTAINERNO, QTY = SUM(ISSUEQTY)
    FROM TBL_IMP_WMS_GOODSISSUE_DTLS
    GROUP BY FK_ITEMID, CONTAINERNO),
RTN AS (
    SELECT FK_ITEMID, CONTAINERNO, QTY = SUM(RETURNQTY)
    FROM TBL_IMP_WMS_GOODSRETURN_DTLS
    GROUP BY FK_ITEMID, CONTAINERNO)
SELECT S.EAN, S.FK_ITEMID, S.containerno,
       stored_currentstock = ISNULL(S.CURRENTSTOCK, 0),
       stored_balancestock = ISNULL(S.BALANCESTOCK, 0),
       grn_qty = ISNULL(G.QTY, 0),
       issued  = ISNULL(I.QTY, 0),
       returned= ISNULL(R.QTY, 0),
       new_stock = ISNULL(G.QTY,0) - ISNULL(I.QTY,0) + ISNULL(R.QTY,0)
FROM WMS_ITEM_STOCK_MASTER_COMMON_CONTR S
LEFT JOIN GRN G ON G.FK_ITEMID = S.FK_ITEMID AND G.CONTAINERNO = S.containerno
LEFT JOIN ISS I ON I.FK_ITEMID = S.FK_ITEMID AND I.CONTAINERNO = S.containerno
LEFT JOIN RTN R ON R.FK_ITEMID = S.FK_ITEMID AND R.CONTAINERNO = S.containerno
WHERE ISNULL(S.CURRENTSTOCK,0) <> ISNULL(G.QTY,0) - ISNULL(I.QTY,0) + ISNULL(R.QTY,0)
   OR ISNULL(S.BALANCESTOCK,0) <> ISNULL(G.QTY,0) - ISNULL(I.QTY,0) + ISNULL(R.QTY,0)
ORDER BY ISNULL(S.CURRENTSTOCK,0) - (ISNULL(G.QTY,0) - ISNULL(I.QTY,0) + ISNULL(R.QTY,0)) DESC;

/* 3. flows with NO stock row at all (repair does NOT create these; ~319 combos
      as of 2026-07-10 — decide separately whether they need rows) */
;WITH GRN AS (
    SELECT D.FK_ITEMID, M.CONTAINERNO, QTY = SUM(D.QTY)
    FROM TBL_IMP_WMS_GRN_DTLS D
    INNER JOIN TBL_IMP_WMS_GRN_MASTER M ON M.GRNNO = D.GRNNO
    GROUP BY D.FK_ITEMID, M.CONTAINERNO)
SELECT G.FK_ITEMID, G.CONTAINERNO, G.QTY AS grn_qty
FROM GRN G
WHERE NOT EXISTS (SELECT 1 FROM WMS_ITEM_STOCK_MASTER_COMMON_CONTR S
                  WHERE S.FK_ITEMID = G.FK_ITEMID AND S.containerno = G.CONTAINERNO)
ORDER BY G.QTY DESC;
