
CREATE PROCEDURE [dbo].[USP_IMP_WMS_GOODSISSUE_INSERT_DTLS]   
--DECLARE  
 @ID VARCHAR(2),
 @GINNO VARCHAR(15),  
 @VGUID NVARCHAR(200),  
 @TRACKID INTEGER,  
 @MAKER_ID NVARCHAR(50),  
 @MAKER_IP NVARCHAR(50),  
 @ACTION  NVARCHAR(20)   
  
AS
  /*  
--'01101100202P001 RPI PDG 230 1885 127.0.0.1 UPDATE'  
SELECT @ID ='01101100202P001',  
  @GRNNO ='RPI',  
  @VGUID ='D578107D-59F9-457B-A0D2-B93881110089',  
  @TRACKID ='230',  
  @MAKER_ID ='1885',  
  @MAKER_IP ='127.0.0.1',  
  @ACTION ='UPDATE'  
--*/  
  
DECLARE @CHILDTRACK INT   
  IF OBJECT_ID('TEMPDB..#TMPGOODSISSUE_DTLS ') IS NOT NULL
DROP TABLE  #TMPGOODSISSUE_DTLS 

CREATE TABLE #TMPGOODSISSUE_DTLS (
id INT IDENTITY(1,1),
fk_ginno VARCHAR(15),
fk_itemid INT,
issueqty DECIMAL(18,2),
uom VARCHAR(15),
containerno varchar(30)
)
 
BEGIN  

	
		IF(@ACTION='UPDATE')
			BEGIN
			INSERT INTO  #TMPGOODSISSUE_DTLS select fk_ginno,fk_itemid,issueqty,uom,containerno from
		    TBL_IMP_WMS_GOODSISSUE_DTLS  WHERE FK_GINNO = @GINNO  ORDER BY ID  

			UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK+B.ISSUEQTY) ELSE 0 END,
			A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK+B.ISSUEQTY) ELSE 0 END
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID FROM #TMPGOODSISSUE_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID 
			AND DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID 

			/* common container table */
			UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK+B.ISSUEQTY) ELSE 0 END,
			A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK+B.ISSUEQTY) ELSE 0 END
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM #TMPGOODSISSUE_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND STOCK.containerno=DTLS.containerno 
			AND DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID WHERE A.CONTAINERNO=B.CONTAINERNO
			END
-- Inserting new records into the main table
						INSERT INTO TBL_IMP_WMS_GOODSISSUE_DTLS (
							fk_ginno,
							FK_ITEMID,
							ISSUEQTY,
							UOM,
							EAN,
							BOXNO,
							CONTAINERNO
						)
						SELECT
							@GINNO,
							FK_ITEMID,
							ISSUEQTY,
							UOM,
							EAN,
							BOXNO,
							CONTAINERNO
						FROM
							TBL_IMP_WMS_GOODSISSUE_DTLS_TMP
						WHERE
							VGUID = @VGUID
							AND ISDELETED <> 'Y'
							AND GINDTLSID = 0
					

			 UPDATE TBL_IMP_WMS_GOODSISSUE_DTLS   
		   SET 
		--   TBL_IMP_WMS_GOODSISSUE_DTLS.FK_ITEMID = TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.FK_ITEMID,  
		   TBL_IMP_WMS_GOODSISSUE_DTLS.ISSUEQTY = TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.ISSUEQTY,  
		   TBL_IMP_WMS_GOODSISSUE_DTLS.UOM = TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.UOM,
		   TBL_IMP_WMS_GOODSISSUE_DTLS.BOXNO=TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.BOXNO
		   --TBL_IMP_WMS_GOODSISSUE_DTLS.ADDMODEQTY=TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.ISSUEQTY
		   FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP  
		   WHERE TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.GINDTLSID = TBL_IMP_WMS_GOODSISSUE_DTLS.ID  
		   AND TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.VGUID = @VGUID   AND ISDELETED <> 'Y' 

		   		   /* UPDATING CURRENT & OPENING STOCK */
		
		  	UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK-B.ISSUEQTY) ELSE 0 END,
			A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK-B.ISSUEQTY) ELSE 0 END
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSISSUE_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID 
			AND DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID 
			
		     /* END UPDATING CURRENT STOCK */

			   /* UPDATING CURRENT & OPENING STOCK IN COMMON CONTAINER */
		
		  	UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK-B.ISSUEQTY) ELSE 0 END,
			A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK-B.ISSUEQTY) ELSE 0 END
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSISSUE_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID  AND STOCK.containerno=DTLS.containerno 
			AND DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID  WHERE A.CONTAINERNO=B.CONTAINERNO
			
		     /* END UPDATING CURRENT STOCK */


		 --INSERT INTO TBL_IMP_WMS_GOODSISSUE_DTLS  (fk_ginno,FK_ITEMID,ISSUEQTY,UOM,EAN,BOXNO)
			--  SELECT   
			--  @GINNO,
			--  FK_ITEMID,
			--  ISSUEQTY,
			--  UOM,
			--  EAN,
			--  BOXNO

			-- FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP  
		 --WHERE VGUID = @VGUID AND ISDELETED <> 'Y'  AND GINDTLSID = '0'  ORDER BY ID  
		
  
			DELETE FROM TBL_IMP_WMS_GOODSISSUE_DTLS  WHERE FK_GINNO = @GINNO
			AND ID IN (SELECT GINDTLSID FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP WHERE VGUID = @VGUID AND ISDELETED = 'Y')  

			
		   	UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK+B.ISSUEQTY) ELSE 0 END,
			A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK+B.ISSUEQTY) ELSE 0 END
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT DTLS.ISSUEQTY,DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND VGUID = @VGUID AND ISDELETED = 'Y'
			AND DTLS.FK_GINNO=@GINNO) B
			ON A.FK_ITEMID=B.FK_ITEMID 

			/* UPDATING COMMON CONTAINER STOCK AFTER DELETION */ 
			 	UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK+B.ISSUEQTY) ELSE 0 END,
			A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK+B.ISSUEQTY) ELSE 0 END
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT ISSUEQTY=SUM(DTLS.ISSUEQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND VGUID = @VGUID AND ISDELETED = 'Y' AND STOCK.containerno=DTLS.containerno 
			AND DTLS.FK_GINNO=@GINNO GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID WHERE A.CONTAINERNO=B.CONTAINERNO

			 INSERT INTO TBL_USERTRACK_WMS_DETAILS(  
				   FKTRACKID, USERID, [DATETIME],  MODE, TABLENAME,  COLUMNNAME,    
				   ORIGINALDATA, MODIFIEDDATA, RECORDID, LOCALIPADD,  ROUTERIPADD)       
				  SELECT  @TRACKID,@MAKER_ID,GETDATE(),   
					CASE WHEN GINDTLSID <> '0' AND ISDELETED = 'Y' THEN 'DELETE'    
					 WHEN GINDTLSID = '0' AND ISDELETED <> 'Y' THEN 'ADD'   
					 ELSE 'EDIT'  
				     END,  
				   'TBL_IMP_WMS_GOODSISSUE_DTLS',  
				   USERTRACK_COLUMNNAME,  
				   --@ENTRYNO +   
				   USERTRACK_ORIGINALDATA,  
				   USERTRACK_MODIFIEDDATA,  
				   @GINNO,--ACC_PURCHASEDTLS_ID,  
				   @MAKER_IP,  
				   ''  
				 FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP   
				 WHERE VGUID = @VGUID --AND ISNULL(USERTRACK_MODIFIEDDATA,'') <> '' AND ACC_PURCHASEDTLS_ID='0'     
				   AND ((ISNULL(USERTRACK_MODIFIEDDATA,'') <> '' AND  GINDTLSID<>'0') OR   
					 (ISDELETED='Y' AND GINDTLSID <> '0') OR   
					 (GINDTLSID = '0' AND ISDELETED <> 'Y'))  
		END  
  
IF @ACTION = 'INSERT'  
		BEGIN  
		 DELETE FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP WHERE VGUID = @VGUID  
		END  
ELSE --IF @ACTION = 'UPDATE'  
BEGIN  
  	DELETE FROM TBL_IMP_WMS_GOODSISSUE_DTLS_TMP WHERE VGUID = @VGUID  
  BEGIN  
	 INSERT INTO TBL_IMP_WMS_GOODSISSUE_DTLS_TMP  
		SELECT FK_GINNO,
		FK_ITEMID,
		ISSUEQTY,
		UOM,
		GIDTLS.ID,  
		'',  
		'N',
        'GINNO|FK_ITEMID|QTY|UOM|SIZE', 
		FK_GINNO + '|' + CONVERT(VARCHAR,FK_ITEMID)  + '|' +  CONVERT(VARCHAR,ISSUEQTY) + '|' +  CONVERT(VARCHAR,UOM)  ,
		'',
        @MAKER_ID,
		@VGUID,
		EAN,
		BOXNO=GIDTLS.BOXNO,
		ISSUEQTY,
		ISNULL(ACKNO,''),GIDTLS.CONTAINERNO
		FROM TBL_IMP_WMS_GOODSISSUE_DTLS   GIDTLS
		INNER JOIN TBL_IMP_WMS_GOODSISSUE_MST GIMST ON GIMST.GINNO=GIDTLS.FK_GINNO
		WHERE GIDTLS.FK_GINNO = @GINNO     
		ORDER BY GIDTLS .ID    
 END  
END  
  
