


CREATE PROCEDURE [dbo].[USP_IMP_WMS_GRN_INSERT_DTLS_MANUAL]   
--DECLARE  
 @ID int,
 @GRNNO VARCHAR(15),  
 @VGUID NVARCHAR(200),  
 @TRACKID INTEGER,  
 @MAKER_ID NVARCHAR(50),  
 @MAKER_IP NVARCHAR(50),  
 @ACTION  NVARCHAR(20) ,
 @CONTAINERNO VARCHAR(30)
  
AS
  /*  
--'01101100202P001 RPI PDG 230 1885 127.0.0.1 UPDATE'  
SELECT @ID ='01101100202P001',  
  @GRNNO ='RPI',  
  @VGUID ='D578107D-59F9-457B-A0D2-B93881110089',  
  @TRACKID ='230',  
  @MAKER_ID ='1885',  
  @MAKER_IP ='127.0.0.1',  
  @ACTION ='UPDATE'  
--*/  
    IF OBJECT_ID('TEMPDB..#TMPGRN_DTLS ') IS NOT NULL
DROP TABLE  #TMPGRN_DTLS

CREATE TABLE #TMPGRN_DTLS (
id INT IDENTITY(1,1),
fk_grnno VARCHAR(15),
fk_itemid INT,
prevqty INT,
EAN varchar(13),
Boxno varchar(20)
) 
  
 
BEGIN  
			IF(@ACTION='UPDATE')
			BEGIN

			INSERT INTO  #TMPGRN_DTLS select GRNNO,fk_itemid,QTY,EAN,isnull(Boxno,'') from
		    TBL_IMP_WMS_GRN_DTLS  WHERE GRNNO = @GRNNO  ORDER BY ID 
			 
			UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK-B.PREVQTY) ELSE 0 END,
			A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK-B.PREVQTY) ELSE 0 END
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT DTLS.PREVQTY,DTLS.FK_ITEMID FROM #TMPGRN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID 
			AND DTLS.FK_GRNNO=@GRNNO) B
			ON A.FK_ITEMID=B.FK_ITEMID 

			--UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK-B.PREVQTY) ELSE 0 END,
			--A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK-B.PREVQTY) ELSE 0 END
			--FROM	WMS_ITEM_STOCK_MASTER_CONTR A INNER JOIN 
			--(SELECT DTLS.PREVQTY,DTLS.FK_ITEMID FROM #TMPGRN_DTLS  DTLS
			--INNER JOIN WMS_ITEM_MASTER_CONTR ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			--INNER JOIN WMS_ITEM_STOCK_MASTER_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			--WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID 
			--AND DTLS.FK_GRNNO=@GRNNO AND ITEMMST.CONTAINERNO=@CONTAINERNO) B
			--ON A.FK_ITEMID=B.FK_ITEMID 
			UPDATE  A SET A.CURRENTSTOCK=CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK-B.PREVQTY) ELSE 0 END,
			A.BALANCESTOCK=CASE WHEN A.BALANCESTOCK > 0 THEN (A.BALANCESTOCK-B.PREVQTY) ELSE 0 END
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT DTLS.PREVQTY,DTLS.FK_ITEMID,GRNMST.CONTAINERNO FROM #TMPGRN_DTLS  DTLS
			INNER JOIN TBL_IMP_WMS_GRN_MASTER GRNMST ON GRNMST.GRNNO= DTLS.FK_GRNNO
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID 
			AND DTLS.FK_GRNNO=@GRNNO AND STOCK.CONTAINERNO=@CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID AND A.CONTAINERNO=B.CONTAINERNO

			UPDATE A SET A.BALQTY=CONVERT(INT,A.BALQTY)+B.PREVQTY FROM 
			WMS_ITEM_MASTER_UPLOAD A INNER JOIN
			#TMPGRN_DTLS B ON B.EAN=A.EAN
			WHERE B.FK_GRNNO=@GRNNO AND A.CONTAINERNO=@CONTAINERNO

			UPDATE A SET A.BALQTY=CONVERT(INT,A.BALQTY)+B.PREVQTY FROM 
			WMS_ITEM_MASTER_MRPLABEL A INNER JOIN
			#TMPGRN_DTLS B ON B.EAN=A.EAN AND A.CONTAINERNO=@CONTAINERNO AND A.BOXNO=B.BOXNO
			WHERE B.FK_GRNNO=@GRNNO --AND A.CONTAINERNO=@CONTAINERNO

			END
										
		 INSERT INTO TBL_IMP_WMS_GRN_DTLS  
			  SELECT   
			  @ID,
			  @GRNNO,
			  FK_ITEMID,
			  FK_ITEMGRPID,
			  FK_ITEMSUBGRPID,
			  ITEMSIZE,
			  QTY,
			  UOM,
			  ORDERNO,
			  WHCODE,
			  RACKNO,
			  EAN,
			  BOXNO
			  	
			 FROM TBL_IMP_WMS_GRN_DTLS_TMP  
		     WHERE VGUID = @VGUID AND ISDELETED <> 'Y'  AND GRNDTLSID = '0'  ORDER BY ID     

			 --IF EXISTS( SELECT ID FROM TBL_IMP_WMS_GRN_DTLS_TMP  WHERE VGUID = @VGUID AND ISDELETED <> 'Y'  AND GRNDTLSID = '0')
			 --BEGIN
				--UPDATE A SET A.BALQTY=A.BALQTY-B.QTY FROM 
				--WMS_ITEM_MASTER_UPLOAD A INNER JOIN
				--TBL_IMP_WMS_GRN_DTLS B ON B.EAN=A.EAN
				--WHERE grnno=@GRNNO AND A.CONTAINERNO=@CONTAINERNO
			 --END
			 	
		   UPDATE TBL_IMP_WMS_GRN_DTLS   
		   SET 
		   TBL_IMP_WMS_GRN_DTLS.FK_ITEMID = TBL_IMP_WMS_GRN_DTLS_TMP.FK_ITEMID,  
		   TBL_IMP_WMS_GRN_DTLS.FK_ITEMGRPID = TBL_IMP_WMS_GRN_DTLS_TMP.FK_ITEMGRPID,  
		   TBL_IMP_WMS_GRN_DTLS.FK_ITEMSUBGRPID = TBL_IMP_WMS_GRN_DTLS_TMP.FK_ITEMSUBGRPID,  
		   TBL_IMP_WMS_GRN_DTLS.ITEMSIZE = TBL_IMP_WMS_GRN_DTLS_TMP.ITEMSIZE,  
		   TBL_IMP_WMS_GRN_DTLS.QTY = TBL_IMP_WMS_GRN_DTLS_TMP.QTY,  
		   TBL_IMP_WMS_GRN_DTLS.UOM = TBL_IMP_WMS_GRN_DTLS_TMP.UOM ,
		   TBL_IMP_WMS_GRN_DTLS.EAN = TBL_IMP_WMS_GRN_DTLS_TMP.EAN, 
		   TBL_IMP_WMS_GRN_DTLS.WHCODE = TBL_IMP_WMS_GRN_DTLS_TMP.WHCODE,
		   TBL_IMP_WMS_GRN_DTLS.RACKNO = TBL_IMP_WMS_GRN_DTLS_TMP.RACKNO
		   FROM TBL_IMP_WMS_GRN_DTLS_TMP  
		   WHERE TBL_IMP_WMS_GRN_DTLS_TMP.GRNDTLSID = TBL_IMP_WMS_GRN_DTLS.ID  
		   AND TBL_IMP_WMS_GRN_DTLS_TMP.VGUID = @VGUID   AND ISDELETED <> 'Y' 
		   
		   /* UPDATING CURRENT & OPENING STOCK */

		   	UPDATE  A SET A.CURRENTSTOCK=(A.CURRENTSTOCK+B.QTY)
			,A.BALANCESTOCK=(ISNULL(A.BALANCESTOCK,0)+B.QTY)
			--CASE WHEN A.CURRENTSTOCK > 0 THEN (A.CURRENTSTOCK+B.QTY) ELSE (A.CURRENTSTOCK+B.QTY) END,
			--A.OPENINGSTOCK=CASE WHEN OPENINGSTOCK=0 THEN A.OPENINGSTOCK+B.QTY ELSE A.OPENINGSTOCK END
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT DTLS.QTY,DTLS.FK_ITEMID FROM TBL_IMP_WMS_GRN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID 
			AND DTLS.FK_ITEMGRPID=ITEMMST.FK_ITEMGRPID  
			--AND DTLS.FK_ITEMSUBGRPID=ITEMMST.FK_ITEMSUBGRPID
			AND DTLS.ITEMSIZE=ITEMMST.SIZE
			AND DTLS.GRNNO=@GRNNO) B
			ON A.FK_ITEMID=B.FK_ITEMID 

			UPDATE  A SET A.CURRENTSTOCK=(A.CURRENTSTOCK+B.QTY)
			,A.BALANCESTOCK=(ISNULL(A.BALANCESTOCK,0)+B.QTY)
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT DTLS.QTY,DTLS.FK_ITEMID,GRNMST.CONTAINERNO FROM TBL_IMP_WMS_GRN_DTLS  DTLS
			INNER JOIN TBL_IMP_WMS_GRN_MASTER GRNMST ON GRNMST.GRNNO= DTLS.GRNNO
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID 
			AND DTLS.FK_ITEMGRPID=ITEMMST.FK_ITEMGRPID  
			--AND DTLS.FK_ITEMSUBGRPID=ITEMMST.FK_ITEMSUBGRPID
			AND DTLS.ITEMSIZE=ITEMMST.SIZE
			AND DTLS.GRNNO=@GRNNO AND STOCK.CONTAINERNO=@CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID  AND A.CONTAINERNO=B.CONTAINERNO


			UPDATE  A SET A.BALQTY=(A.BALQTY-B.QTY)
				 FROM	WMS_ITEM_MASTER_UPLOAD A INNER JOIN 
			(SELECT QTY=SUM(DTLS.QTY),DTLS.FK_ITEMID,DTLS.EAN FROM TBL_IMP_WMS_GRN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID 
			AND DTLS.FK_ITEMGRPID=ITEMMST.FK_ITEMGRPID  
			AND DTLS.ITEMSIZE=ITEMMST.SIZE
			AND DTLS.GRNNO=@GRNNO GROUP BY DTLS.FK_ITEMID,DTLS.EAN) B
			ON A.EAN=B.EAN WHERE    A.CONTAINERNO=@CONTAINERNO


			
			UPDATE  A SET A.BALQTY=(A.BALQTY-B.QTY),A.BOXNO=B.BOXNO
				 FROM	WMS_ITEM_MASTER_MRPLABEL A INNER JOIN 
			(SELECT QTY=SUM(DTLS.QTY),DTLS.FK_ITEMID,DTLS.EAN,DTLS.BOXNO FROM TBL_IMP_WMS_GRN_DTLS  DTLS
			INNER JOIN TBL_IMP_WMS_GRN_MASTER MST ON MST.GRNNO=DTLS.GRNNO
		    WHERE DTLS.GRNNO=@GRNNO GROUP BY DTLS.FK_ITEMID,DTLS.EAN,DTLS.BOXNO) B
			ON A.EAN=B.EAN AND  A.CONTAINERNO=@CONTAINERNO---A.BOXNO=B.BOXNO


			--UPDATE A SET A.BALQTY=A.BALQTY-B.QTY FROM 
			--WMS_ITEM_MASTER_UPLOAD A INNER JOIN
			--TBL_IMP_WMS_GRN_DTLS B ON B.EAN=A.EAN
			--INNER JOIN TBL_IMP_WMS_GRN_DTLS_TMP ON TBL_IMP_WMS_GRN_DTLS_TMP.EAN=B.EAN
			--WHERE B.GRNNO=@GRNNO AND  A.CONTAINERNO=@CONTAINERNO AND ISDELETED <> 'Y' 
			--AND TBL_IMP_WMS_GRN_DTLS_TMP.grndtlsid<>0

		

		     /* END UPDATING CURRENT & OPENING STOCK */

  			DELETE FROM TBL_IMP_WMS_GRN_DTLS  WHERE GRNNO = @GRNNO
			AND ID IN (SELECT GRNDTLSID FROM TBL_IMP_WMS_GRN_DTLS_TMP WHERE VGUID = @VGUID AND ISDELETED = 'Y')  

			
		   	UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK-B.QTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)-B.QTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT DTLS.QTY,DTLS.FK_ITEMID FROM TBL_IMP_WMS_GRN_DTLS_TMP  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND VGUID = @VGUID AND ISDELETED = 'Y'
			AND DTLS.FK_ITEMGRPID=ITEMMST.FK_ITEMGRPID  
			--AND DTLS.FK_ITEMSUBGRPID=ITEMMST.FK_ITEMSUBGRPID
			AND DTLS.ITEMSIZE=ITEMMST.SIZE
			AND DTLS.GRNNO=@GRNNO) B
			ON A.FK_ITEMID=B.FK_ITEMID 


			UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK-B.QTY,
			A.BALANCESTOCK=ISNULL(A.BALANCESTOCK,0)-B.QTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT DTLS.QTY,DTLS.FK_ITEMID,GRNMST.CONTAINERNO FROM TBL_IMP_WMS_GRN_DTLS_TMP  DTLS
			INNER JOIN TBL_IMP_WMS_GRN_MASTER GRNMST ON GRNMST.GRNNO= DTLS.GRNNO
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND VGUID = @VGUID AND ISDELETED = 'Y'
			AND DTLS.FK_ITEMGRPID=ITEMMST.FK_ITEMGRPID  
			--AND DTLS.FK_ITEMSUBGRPID=ITEMMST.FK_ITEMSUBGRPID
			AND DTLS.ITEMSIZE=ITEMMST.SIZE
			AND DTLS.GRNNO=@GRNNO AND STOCK.CONTAINERNO=@CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID  AND A.CONTAINERNO=B.CONTAINERNO

     
				 INSERT INTO TBL_USERTRACK_WMS_DETAILS(  
				    FKTRACKID, USERID, [DATETIME],  MODE, TABLENAME,  COLUMNNAME,    
				    ORIGINALDATA, MODIFIEDDATA, RECORDID, LOCALIPADD,  ROUTERIPADD)       
				    SELECT  @TRACKID,@MAKER_ID,GETDATE(),   
					CASE WHEN GRNDTLSID <> '0' AND ISDELETED = 'Y' THEN 'DELETE'    
					WHEN GRNDTLSID = '0' AND ISDELETED <> 'Y' THEN 'ADD'  ELSE 'EDIT'   END,  
				   'TBL_IMP_WMS_GRN_DTLS',  
				    USERTRACK_COLUMNNAME,  
				   --@ENTRYNO +   
				    USERTRACK_ORIGINALDATA,  
				    USERTRACK_MODIFIEDDATA,  
				    @GRNNO,--ACC_PURCHASEDTLS_ID,  
				    @MAKER_IP,  
				    ''  
				 FROM TBL_IMP_WMS_GRN_DTLS_TMP   
					WHERE VGUID = @VGUID --AND ISNULL(USERTRACK_MODIFIEDDATA,'') <> '' AND ACC_PURCHASEDTLS_ID='0'     
				    AND ((ISNULL(USERTRACK_MODIFIEDDATA,'') <> '' AND  GRNDTLSID<>'0') OR   
				    (ISDELETED='Y' AND GRNDTLSID <> '0') OR   
				    (GRNDTLSID = '0' AND ISDELETED <> 'Y'))  
		END  
  
IF @ACTION = 'INSERT'  
		BEGIN  
		 DELETE FROM TBL_IMP_WMS_GRN_DTLS_TMP WHERE VGUID = @VGUID  
		END  
ELSE --IF @ACTION = 'UPDATE'  
BEGIN  
     	DELETE FROM TBL_IMP_WMS_GRN_DTLS_TMP WHERE VGUID = @VGUID  
    BEGIN  
	    INSERT INTO TBL_IMP_WMS_GRN_DTLS_TMP  
		SELECT TBL_IMP_WMS_GRN_DTLS.GRNNO,
		FK_ITEMID,
		FK_ITEMGRPID,
		FK_ITEMSUBGRPID,
		ITEMSIZE,
		QTY,
		UOM,
		TBL_IMP_WMS_GRN_DTLS.ID,  
		'',  
		'N',
        'GRNNO|FK_ITEMID|FK_ITEMGRPID|FK_ITEMSUBGRPID|ITEMSIZE|QTY|UOM|SIZE', 
		 TBL_IMP_WMS_GRN_DTLS.GRNNO + '|' + CONVERT(VARCHAR,FK_ITEMID)  + '|' + CONVERT(VARCHAR,FK_ITEMSUBGRPID)  + '|'  + CONVERT(VARCHAR,ITEMSIZE)  
		 + '|' +  CONVERT(VARCHAR,QTY) + '|' +  CONVERT(VARCHAR,UOM)  ,
		  '',
         @MAKER_ID,
		 @VGUID,
		 TBL_IMP_WMS_GRN_DTLS.ORDERNO,
		 ISNULL(WHCODE,''),
		 ISNULL(RACKNO,''),
		 ISNULL(EAN,''),
		QTY,
		ENTRYSTARTDTTIME=ISNULL(TBL_IMP_WMS_GRN_MASTER.ENTRYSTARTDTTIME,''),
		BOXNO=ISNULL(TBL_IMP_WMS_GRN_DTLS.BOXNO,'')
		FROM TBL_IMP_WMS_GRN_DTLS  
		INNER JOIN TBL_IMP_WMS_GRN_MASTER ON TBL_IMP_WMS_GRN_MASTER.GRNNO=TBL_IMP_WMS_GRN_DTLS.GRNNO
		WHERE TBL_IMP_WMS_GRN_DTLS.GRNNO = @GRNNO     
		ORDER BY TBL_IMP_WMS_GRN_DTLS .ID    
 END  
END  
  
