


CREATE PROCEDURE [dbo].[USP_IMP_WMS_GOODSRETURN_BULKINSERT_CSV]

--DECLARE
    --@ExcelPath NVARCHAR(500),   -- Full file path
    --@SheetName NVARCHAR(100),
	@FILEPATH VARCHAR(150),
	@FILENAME VARCHAR(200),
	@FK_LOGID INT,
	@CLIENT VARCHAR(12),
	@CLIENTADDID INT,
	@GRTNDATE VARCHAR(10),
	@RETURNDATE VARCHAR(100),
	@RETURNNO VARCHAR(100),
	@CLIENTINVNO VARCHAR(100),
	@CMPCODE VARCHAR(2),
	@CITYCODE VARCHAR(3),
	@CITYCODE1 VARCHAR(3),
	@MAKERID INT,
	@MAKERIP VARCHAR(50)----,
	----@REMARK VARCHAR(50)
	
	

AS

--DROP TABLE #TempExcelData
--SELECT  @FILEPATH='D:\Application\Manilal_Projects\Manilal_V5NG_API\DATA\WMS\GoodsReturn\RO0002382429_1.csv',@FILENAME='RO0002382429_1',@returnno='RO0002382429',@CLIENTINVNO='S2926IL000000006',
--@MAKERID=1885,@MAKERIP='::1',@client='E112990',@CLIENTADDID=14336,@CMPCODE='01',@CITYCODE='MUM',@CITYCODE1='101',
--@RETURNDATE='2025-01-29 02:32:00.000',@GRTNDATE='13/08/2025',@FK_LOGID=1
BEGIN
    SET NOCOUNT ON;

	 DECLARE @SQL NVARCHAR(MAX);
 IF OBJECT_ID('TEMPDB..#TempExcelData') IS NOT NULL
DROP TABLE  #TempExcelData
    /* Temp table */
    CREATE TABLE #TempExcelData
    (
	  
        [DATE]  VARCHAR(20),
        FRMLOCATION  VARCHAR(15),
        EAN  VARCHAR(15),
        KIABICODE  VARCHAR(100),
        BOXNO  VARCHAR(100),
        PIECES  VARCHAR(100),
        INVNO  VARCHAR(100),
        RONO  VARCHAR(100),
        REMARK  VARCHAR(200),
        TRACKINGNO VARCHAR(100)
    );

SET @SQL = '
BULK INSERT #TempExcelData
FROM ''' + @FILEPATH + '''
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = '','',
    ROWTERMINATOR = ''\n''
)';


  EXEC sp_executesql @SQL;
    /* You can now use the temp table */
    --SELECT * FROM #TempExcelData ---where ----n='3616039368249';
	--SELECT * FROM #TempExcelData WHERE EAN='3616034809570' ORDER BY RONO

	--SELECT * FROM #TempExcelData
--END
	
	DECLARE	 @PRECODE AS VARCHAR(15)
				,@INTCNT AS INT
				,@RIGHTNUM AS VARCHAR(10)
				,@VOUCHERTYPE AS VARCHAR(3),
				@GRTNNO  VARCHAR(15)

			SET @VOUCHERTYPE = 'GRTIN' 
			
		SET @PRECODE =	 SUBSTRING(@CMPCODE,2,1) + @CITYCODE1 + @VOUCHERTYPE 
						+ SUBSTRING(@GRTNDATE, 9, 2)
						+ SUBSTRING(@GRTNDATE, 4, 2) 
					
						 
	
	
		EXEC [DBO].[USP_IMP_WMS_INSERT_CODE] 'GRTN', @PRECODE,  @GRTNNO OUTPUT

		INSERT INTO TBL_IMP_WMS_GOODSRETURN_MST
				(
					GRTNNO,
					GRTNDATE,
					CLIENT,
					CLIENTADDID,
					RETURNNO,
					CLIENTINVNO,
					RETURNDATE,
					---REMARK,
					MAKERID,
					MAKERDT,
					MAKERIP,
					CMPCODE,
					CITYCODE,
					SCANTYPE
				)
				VALUES
				(   
					@GRTNNO,
					@GRTNDATE,
					@CLIENT,
					@CLIENTADDID,
					@RETURNNO,
					@CLIENTINVNO,
					--@RETURNDATE,
					CASE WHEN @RETURNDATE='' THEN NULL ELSE CONVERT(DATETIME,@RETURNDATE,103)END,
					---@REMARK,
					@MAKERID,
					GETDATE(),
					@MAKERIP,
					@CMPCODE,
					@CITYCODE,
					'E'
				)
				
				INSERT INTO TBL_IMP_WMS_GOODSRETURN_DTLS (
							fk_grtnno,
							FK_ITEMID,
							RETURNQTY,
							UOM,
							EAN,
							FK_RETURNREASON,
							FK_RETURNTYPE,
							CONTAINERNO,
							BOXNO,
							KIABICODE
						)
						SELECT
							@GRTNNO,
							PK_ITEMID,
							PIECES=SUM(CONVERT(INT,PIECES)),
							'PIECES',
							#TempExcelData.EAN,
							1,  ---RETURNREASON
							3,  ----RETURNTYPE
							dbo.GetContainerNoforGoodsReturn(#TempExcelData.EAN) AS CONTAINERNO,
							ISNULL(BOXNO,''),
							ISNULL(KIABICODE,'')
							FROM
							#TempExcelData  INNER JOIN
							WMS_ITEM_MASTER ON  WMS_ITEM_MASTER.EAN=#TempExcelData.EAN
							GROUP BY 
							PK_ITEMID,
							#TempExcelData.EAN,
							dbo.GetContainerNoforGoodsReturn(#TempExcelData.EAN),
							BOXNO,
							KIABICODE

		 /* UPDATING CURRENT & OPENING STOCK */
		
		  	UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK+B.RETURNQTY,
			A.BALANCESTOCK=A.BALANCESTOCK+B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSRETURN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID 
			
		     /* END UPDATING CURRENT STOCK */

			 	 /* UPDATING CURRENT & OPENING STOCK IN COMMON CONTAINER */
		
		  	UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK+B.RETURNQTY,
			A.BALANCESTOCK=A.BALANCESTOCK+B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSRETURN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID AND A.CONTAINERNO=B.CONTAINERNO  

			SELECT '100' STATUS ,  MSG= @GRTNNO + ' GENERATED SUCCESSFULLY' --@FILENAME + ' UPLOADED SUCCESSFULLY' 
END
