

CREATE PROCEDURE [dbo].[USP_IMP_WMS_GOODSRETURN_INSERT_DTLS]   
--DECLARE  
 @ID VARCHAR(2),
 @GRTNNO VARCHAR(15),  
 @VGUID NVARCHAR(200),  
 @TRACKID INTEGER,  
 @MAKER_ID NVARCHAR(50),  
 @MAKER_IP NVARCHAR(50),  
 @ACTION  NVARCHAR(20)   
  
AS  /*  

SELECT @ID ='4',  
  @GRTNNO ='1101GRT24070001',  
  @VGUID ='8bb6a478-15af-4188-82d1-6c4782721a0a',  
  @TRACKID ='11',  
  @MAKER_ID ='1885',  
  @MAKER_IP ='::1',  
  @ACTION ='UPDATE'  
--*/  
  
DECLARE @CHILDTRACK INT   
  IF OBJECT_ID('TEMPDB..#TMPGOODSRETURN_DTLS') IS NOT NULL
DROP TABLE  #TMPGOODSRETURN_DTLS 

CREATE TABLE #TMPGOODSRETURN_DTLS (
id INT IDENTITY(1,1),
fk_grtnno VARCHAR(15),
fk_itemid INT,
returnqty DECIMAL(18,2),
uom VARCHAR(15),
FK_RETURNREASON int,
containerno varchar(30)
)
 
BEGIN  

	
		IF(@ACTION='UPDATE')
			BEGIN
			INSERT INTO  #TMPGOODSRETURN_DTLS select fk_grtnno,fk_itemid,returnqty,uom,FK_RETURNREASON,containerno from
		    TBL_IMP_WMS_GOODSRETURN_DTLS  WHERE FK_GRTNNO = @GRTNNO  ORDER BY ID  

			UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK-B.RETURNQTY,
			A.BALANCESTOCK=A.BALANCESTOCK-B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID FROM #TMPGOODSRETURN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID 

			UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK-B.RETURNQTY,
			A.BALANCESTOCK=A.BALANCESTOCK-B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM #TMPGOODSRETURN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO   GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID AND A.CONTAINERNO=B.CONTAINERNO 
			END
-- Inserting new records into the main table
						INSERT INTO TBL_IMP_WMS_GOODSRETURN_DTLS (
							fk_grtnno,
							FK_ITEMID,
							RETURNQTY,
							UOM,
							EAN,
							FK_RETURNREASON,
							FK_RETURNTYPE,
							CONTAINERNO,
							BOXNO,
							KIABICODE
						)
						SELECT
							@GRTNNO,
							FK_ITEMID,
							RETURNQTY,
							UOM,
							EAN,
							FK_RETURNREASON,
							FK_RETURNTYPE,
							CONTAINERNO,
							ISNULL(BOXNO,''),
							ISNULL(KIABICODE,'')
							FROM
							TBL_IMP_WMS_GOODSRETURN_DTLS_TMP
						WHERE
							VGUID = @VGUID
							AND ISDELETED <> 'Y'
							AND GRTNDTLSID = 0
					

			 UPDATE TBL_IMP_WMS_GOODSRETURN_DTLS   
		   SET 
		   TBL_IMP_WMS_GOODSRETURN_DTLS.FK_ITEMID = TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.FK_ITEMID,  
		   TBL_IMP_WMS_GOODSRETURN_DTLS.RETURNQTY = TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.RETURNQTY,  
		   TBL_IMP_WMS_GOODSRETURN_DTLS.UOM = TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.UOM
		   --TBL_IMP_WMS_GOODSISSUE_DTLS.ADDMODEQTY=TBL_IMP_WMS_GOODSISSUE_DTLS_TMP.ISSUEQTY
		   FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP  
		   WHERE TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.GRTNDTLSID =TBL_IMP_WMS_GOODSRETURN_DTLS.ID  
		   AND TBL_IMP_WMS_GOODSRETURN_DTLS_TMP.VGUID = @VGUID   AND ISDELETED <> 'Y' 

		   	 /* UPDATING CURRENT & OPENING STOCK */
		
		  	UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK+B.RETURNQTY,
			A.BALANCESTOCK=A.BALANCESTOCK+B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSRETURN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO GROUP BY DTLS.FK_ITEMID) B
			ON A.FK_ITEMID=B.FK_ITEMID 
			
		     /* END UPDATING CURRENT STOCK */

			 	 /* UPDATING CURRENT & OPENING STOCK IN COMMON CONTAINER */
		
		  	UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK+B.RETURNQTY,
			A.BALANCESTOCK=A.BALANCESTOCK+B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT RETURNQTY=SUM(DTLS.RETURNQTY),DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSRETURN_DTLS  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO GROUP BY DTLS.FK_ITEMID,DTLS.CONTAINERNO) B
			ON A.FK_ITEMID=B.FK_ITEMID AND A.CONTAINERNO=B.CONTAINERNO
			
		     /* END UPDATING CURRENT STOCK */


		
  
			DELETE FROM TBL_IMP_WMS_GOODSRETURN_DTLS  WHERE FK_GRTNNO = @GRTNNO
			AND ID IN (SELECT GRTNDTLSID FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP WHERE VGUID = @VGUID AND ISDELETED = 'Y')  

			
		   	UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK-B.RETURNQTY,
			A.BALANCESTOCK=A.BALANCESTOCK-B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER A INNER JOIN 
			(SELECT DTLS.RETURNQTY,DTLS.FK_ITEMID FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND VGUID = @VGUID AND ISDELETED = 'Y' AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO) B
			ON A.FK_ITEMID=B.FK_ITEMID  

			/* IN COMMON CONTAINER */
			UPDATE  A SET A.CURRENTSTOCK=A.CURRENTSTOCK-B.RETURNQTY,
			A.BALANCESTOCK=A.BALANCESTOCK-B.RETURNQTY
			FROM	WMS_ITEM_STOCK_MASTER_COMMON_CONTR A INNER JOIN 
			(SELECT DTLS.RETURNQTY,DTLS.FK_ITEMID,DTLS.CONTAINERNO FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP  DTLS
			INNER JOIN WMS_ITEM_MASTER ITEMMST ON ITEMMST.PK_ITEMID=DTLS.FK_ITEMID
			INNER JOIN WMS_ITEM_STOCK_MASTER_COMMON_CONTR STOCK ON ITEMMST.PK_ITEMID=STOCK.FK_ITEMID
			WHERE  DTLS.FK_ITEMID=STOCK.FK_ITEMID AND VGUID = @VGUID AND ISDELETED = 'Y' AND DTLS.FK_RETURNREASON=1
			AND DTLS.FK_GRTNNO=@GRTNNO) B
			ON A.FK_ITEMID=B.FK_ITEMID  AND A.CONTAINERNO=B.CONTAINERNO


     
			 INSERT INTO TBL_USERTRACK_DETAILS(  
				   FKTRACKID, USERID, [DATETIME],  MODE, TABLENAME,  COLUMNNAME,    
				   ORIGINALDATA, MODIFIEDDATA, RECORDID, LOCALIPADD,  ROUTERIPADD)       
				  SELECT  @TRACKID,@MAKER_ID,GETDATE(),   
					CASE WHEN GRTNDTLSID <> '0' AND ISDELETED = 'Y' THEN 'DELETE'    
					 WHEN GRTNDTLSID = '0' AND ISDELETED <> 'Y' THEN 'ADD'   
					 ELSE 'EDIT'  
				     END,  
				   'TBL_IMP_WMS_GOODSRETURN_DTLS',  
				   USERTRACK_COLUMNNAME,  
				   --@ENTRYNO +   
				   USERTRACK_ORIGINALDATA,  
				   USERTRACK_MODIFIEDDATA,  
				   @GRTNNO,--ACC_PURCHASEDTLS_ID,  
				   @MAKER_IP,  
				   ''  
				 FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP   
				 WHERE VGUID = @VGUID --AND ISNULL(USERTRACK_MODIFIEDDATA,'') <> '' AND ACC_PURCHASEDTLS_ID='0'     
				   AND ((ISNULL(USERTRACK_MODIFIEDDATA,'') <> '' AND  GRTNDTLSID<>'0') OR   
					 (ISDELETED='Y' AND GRTNDTLSID <> '0') OR   
					 (GRTNDTLSID = '0' AND ISDELETED <> 'Y'))  
		END  
  
IF @ACTION = 'INSERT'  
		BEGIN  
		 DELETE FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP WHERE VGUID = @VGUID  
		END  
ELSE --IF @ACTION = 'UPDATE'  
BEGIN  
  	DELETE FROM TBL_IMP_WMS_GOODSRETURN_DTLS_TMP WHERE VGUID = @VGUID  
  BEGIN  
	 INSERT INTO TBL_IMP_WMS_GOODSRETURN_DTLS_TMP  
		SELECT FK_GRTNNO,
		FK_ITEMID,
		RETURNQTY,
		UOM,
		EAN,
		FK_RETURNREASON,
		FK_RETURNTYPE,
		GIDTLS.ID,  
		'',  
		'N',
        'GRTNNO|FK_ITEMID|QTY|UOM|SIZE', 
		 fk_grtnno + '|' + CONVERT(VARCHAR,FK_ITEMID)  + '|' +  CONVERT(VARCHAR,RETURNQTY) + '|' +  CONVERT(VARCHAR,UOM)  ,
		'',
        @MAKER_ID,
		@VGUID,
		CONTAINERNO,
		ISNULL(BOXNO,''),
		ISNULL(KIABICODE,'')
	
		FROM TBL_IMP_WMS_GOODSRETURN_DTLS   GIDTLS
		INNER JOIN TBL_IMP_WMS_GOODSRETURN_MST GIMST ON GIMST.GRTNNO=GIDTLS.FK_GRTNNO
		WHERE GIDTLS.FK_GRTNNO = @GRTNNO     
		ORDER BY GIDTLS .ID    
 END  
END  
  
